#
# Makefile for the touchscreen drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_TOUCHSCREEN_GSLX680) += gslX680.o
obj-$(CONFIG_TOUCHSCREEN_GSLX680_ANTI_SHAKE) += point_active_pen_0x20150706_no_gesture.o
